services:
  database:
    image: postgres:15.5
    container_name: 'tmpcode-database'
    environment:
      - POSTGRES_DB=tmpcodes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d tmpcodes' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - 'database:/var/lib/postgresql/data'
      - './sql:/docker-entrypoint-initdb.d'
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    container_name: server
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
volumes:
  database:
    driver: local
