services:
 server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    container_name: server
    expose:
      - '3000'
    ports:
      - '3000:3000'
volumes:
  database:
    driver: local
